version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
#    command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn config.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://raufmasoumi:secret@postgres:5432/BookStore

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=raufmasoumi
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=BookStore

volumes:
  postgres_data: