# Generated by Django 4.0.1 on 2022-01-09 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ffcfc4ed-5400-4786-84e0-9c3d6f438285'), editable=False, primary_key=True, serialize=False),
        ),
    ]
