# Generated by Django 4.0.3 on 2022-06-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Published'), ('d', 'Draft')], default='p', max_length=1),
        ),
    ]
