# Generated by Django 4.0.1 on 2022-01-09 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('be57885b-fef9-4bce-9280-16e2bd49cba0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
