# Generated by Django 4.0.1 on 2022-01-09 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3cd74d3e-664b-454d-aeae-022a1bed24de'), editable=False, primary_key=True, serialize=False),
        ),
    ]
