# Generated by Django 4.0.1 on 2022-01-10 13:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0216c9b0-93c0-4f00-8598-89501010a942'), editable=False, primary_key=True, serialize=False),
        ),
    ]
