# Generated by Django 4.0.5 on 2023-07-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='page size'),
        ),
    ]
