# Generated by Django 4.0.1 on 2022-01-10 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('46c9abc2-20b8-4df5-a60e-67d314d0b90c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
