# Generated by Django 4.0.5 on 2023-07-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_page_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_size',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='page size'),
        ),
    ]
