# Generated by Django 4.0.1 on 2022-01-10 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('13b2a059-a26b-42e7-85e0-b798e9014fe0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
