# Generated by Django 4.0.1 on 2022-01-10 14:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9464deb6-a315-47dd-bc92-8e2fe60bf01b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
