# Generated by Django 4.0.1 on 2022-01-13 15:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a1dc4f03-9901-49d8-8044-12fbb95253cc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
