# Generated by Django 4.0.1 on 2022-01-13 15:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('abfe6d2e-9306-47d7-ac55-df75fd15cca8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
