# Generated by Django 4.0.1 on 2022-01-16 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('30dc2e19-1358-4dd1-81b7-3d9f5fc5a774'), editable=False, primary_key=True, serialize=False),
        ),
    ]
