# Generated by Django 4.0.1 on 2022-01-16 22:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6ed6270b-b6b6-4026-aa37-c3e6155b588f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
