# Generated by Django 4.0.1 on 2022-01-17 21:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dbcb6ffa-b932-4628-96f4-1a2199e2cd39'), editable=False, primary_key=True, serialize=False),
        ),
    ]
