# Generated by Django 4.0.1 on 2022-01-19 19:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_book_id_alter_book_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ac0b1220-5f7b-4b55-b2f7-e2ba1b3e7832'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
