# Generated by Django 4.0.1 on 2022-01-19 20:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_book_id_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7b028da5-99dc-462b-aca4-c00bac2cbd39'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=250),
        ),
    ]
