# Generated by Django 4.0.1 on 2022-01-21 07:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_book_id_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9a68dd8f-ba31-48bc-a1e8-c06f99100750'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
