# Generated by Django 4.0.1 on 2022-01-21 19:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_book_id_alter_book_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8d7162e8-3e54-4ac8-98e5-79f01ba56202'), editable=False, primary_key=True, serialize=False),
        ),
    ]
