# Generated by Django 4.0.1 on 2022-01-25 15:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_reviewreply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['submitted']},
        ),
        migrations.AlterModelOptions(
            name='reviewreply',
            options={'ordering': ['replied'], 'verbose_name_plural': 'ReviewReplies'},
        ),
        migrations.AddField(
            model_name='book',
            name='buys',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('hello', (('p', 'Published'),)), ('hi', (('d', 'Draft'),))], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='replied',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='categories')),
                ('status', models.BooleanField(default=True, verbose_name='To be displayed?')),
                ('position', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='books.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['parent_id', 'position'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='books', to='books.Category'),
        ),
    ]
