# Generated by Django 4.0.1 on 2022-01-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_rename_status_category_active_alter_book_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='active',
            new_name='status',
        ),
    ]
