# Generated by Django 4.0.1 on 2022-01-26 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_alter_review_options_alter_reviewreply_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books'), ('published_status', 'Can read published books')]},
        ),
        migrations.AlterModelOptions(
            name='reviewreply',
            options={'ordering': ['replied'], 'verbose_name_plural': 'ReviewReplies'},
        ),
        migrations.AddField(
            model_name='review',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviewreply',
            name='add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_replies', to='books.reviewreply'),
        ),
    ]
