# Generated by Django 4.0.1 on 2022-01-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_book_images_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='images',
            field=models.FileField(blank=True, upload_to='books/images/'),
        ),
    ]
