# Generated by Django 4.0.1 on 2022-01-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0032_alter_bookimage_book_alter_bookimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, max_length=200, upload_to='books/images/'),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.ImageField(default='', max_length=200, upload_to='books/images/'),
            preserve_default=False,
        ),
    ]
