# Generated by Django 4.0.1 on 2022-01-27 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_remove_book_image_alter_bookimage_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='grade_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='length(cm)'),
        ),
        migrations.AddField(
            model_name='book',
            name='page_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='time_to_sell',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='width(cm)'),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.ImageField(blank=True, max_length=200, upload_to='books/images/'),
        ),
    ]
