# Generated by Django 4.0.1 on 2022-01-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0036_alter_book_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateField(blank=True, null=True, verbose_name='published time'),
        ),
    ]
