# Generated by Django 4.0.1 on 2022-02-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0039_alter_book_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-time_to_sell', 'stock'], 'permissions': [('special_status', 'Can read all books')]},
        ),
        migrations.AddField(
            model_name='book',
            name='off',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Published'), ('d', 'Draft')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(blank=True, default=True, verbose_name='To be displayed?'),
        ),
    ]
