# Generated by Django 4.0.1 on 2022-02-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0040_alter_book_options_book_off_alter_book_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sale',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
