# Generated by Django 4.0.1 on 2022-02-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0042_review_email_review_name_alter_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
