# Generated by Django 4.0.1 on 2022-02-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0043_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
