# Generated by Django 4.0.1 on 2022-02-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0044_alter_book_pages_alter_review_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
