# Generated by Django 4.0.1 on 2022-02-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0047_alter_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
