# Generated by Django 4.0.1 on 2022-02-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0048_book_bestseller_book_new_alter_book_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='mostpopular',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='bestseller',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='new',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='sale',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
