# Generated by Django 4.0.3 on 2022-03-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0049_book_mostpopular_alter_book_bestseller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
