# Generated by Django 4.0.3 on 2022-04-18 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0050_book_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['votes', '-submitted']},
        ),
        migrations.AlterModelOptions(
            name='reviewreply',
            options={'ordering': ['votes', '-replied'], 'verbose_name_plural': 'Review Replies'},
        ),
        migrations.RemoveField(
            model_name='reviewreply',
            name='add',
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='addsign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addsign_replies', to='books.reviewreply'),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='email',
            field=models.EmailField(default='raouf.rm93@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='name',
            field=models.CharField(default='guest', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='bestseller',
            field=models.BooleanField(blank=True, default=False, verbose_name='Set as a bestseller book?(will show in bestseller products)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, max_length=300, upload_to='books/covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mostpopular',
            field=models.BooleanField(blank=True, default=False, verbose_name='Set as a mostpopular book?(will show in mostpopular products)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='new',
            field=models.BooleanField(blank=True, default=False, verbose_name='Set as a newarrival book?(will show in newarrival products)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='page size(like A4)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sale',
            field=models.BooleanField(blank=True, default=False, verbose_name='Set as a sale book?(will show in sale products)'),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.ImageField(blank=True, max_length=300, upload_to='books/images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True, verbose_name='To be displayed?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(default='raouf.rm93@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='guest', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='reviewreply',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
