# Generated by Django 4.0.3 on 2022-04-21 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0051_alter_review_options_alter_reviewreply_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent_id', 'position'], 'permissions': [('category_list', 'Can see category list')], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='reviewreply',
            name='addsign',
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='books.reviewreply'),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, default='guest', max_length=50),
        ),
    ]
