# Generated by Django 4.0.3 on 2022-06-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0052_alter_category_options_remove_reviewreply_addsign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='books/covers/unknownbook.png', max_length=300, upload_to='books/covers/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='reviewreply',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='reviewreply',
            name='name',
            field=models.CharField(blank=True, default='guest', max_length=50),
        ),
    ]
