# Generated by Django 4.0.1 on 2022-01-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_id'),
        ('accounts', '0002_customuser_address_customuser_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='cart',
            field=models.ManyToManyField(null=True, related_name='in_carts', to='books.Book'),
        ),
    ]
