# Generated by Django 4.0.1 on 2022-01-16 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_id'),
        ('accounts', '0006_alter_usercart_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCartBooksNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_numbers', to='accounts.usercart')),
            ],
        ),
    ]
