# Generated by Django 4.0.1 on 2022-01-16 22:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usercartbooksnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
