# Generated by Django 4.0.1 on 2022-01-16 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_usercart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='total_price',
        ),
    ]
