# Generated by Django 4.0.1 on 2022-01-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_usercartbooksnumber_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercartbooksnumber',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
