# Generated by Django 4.0.1 on 2022-01-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_usercartbooksnumber_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cash',
        ),
        migrations.AlterField(
            model_name='usercartbooksnumber',
            name='number',
            field=models.PositiveIntegerField(default=1, max_length=2),
        ),
    ]
