# Generated by Django 4.0.1 on 2022-01-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_customuser_cash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercartbooksnumber',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
