# Generated by Django 4.0.1 on 2022-01-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_usercartbooksnumber_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='accounts/pictures/'),
        ),
    ]
