# Generated by Django 4.0.3 on 2022-05-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_useraddress_address_useraddress_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='reciever_first_name',
            new_name='receiver_first_name',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='reciever_last_name',
            new_name='receiver_last_name',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='reciever_phone_number',
            new_name='receiver_phone_number',
        ),
    ]
